#' Generates and downloads files from survey solution's server
#' As for any other function of \code{susor}, \code{susor_export_file} requires
#' that you first define your credentials with \code{susor_credentials()}.For
#' \code{susor_export_file} it is required that you define \code{susor_dir_downloads}
#' in \code{susor_credentials()}. \code{susor_dir_download} will be the diretory
#' where the file will be unzipped and saved. Once that the questionnaire variable
#' \code{susor_qn_variable}, and the version (\code{susor_qn_version}) are defined.
#' \code{susor_export_file} will generate and download all the interviewers from
#' that version of the questionnaire.
#' @return Unzipped file with the file saved in \code{susor_dir_downloads}. Define
#' \code{susor_dir_downloads} in \code{susor_credentials}.
#' @param  susor_qn_variable A string. Variable name of questionnaire, you can
#' find it in the tibble \code{susor_questionnaires} that is created by
#' \code{susor_credentials}.
#' @param susor_qn_version A number. Versions number of the questionnaire
#' to download, this can be found in he tibble \code{susor_questionnaires}
#' that is created by  \code{susor_credentials}.
#' @param susor_format A string to define the format of the file c("STATA", "Tabular").
#' Default = "STATA"
#' @param susor_interview_status A string. To define the status of interviews to download
#' c( "All", "SupervisorAssigned", "InterviewerAssigned", "Completed", "RejectedBySupervisor",
#'  "ApprovedBySupervisor", "RejectedByHeadquarters", "ApprovedByHeadquarters").
#'  Default = "ALL"
#' @param  temporary_dir A temporary directory where the .zip format from the
#' API export response is temporally stored and unzipped from.
#' @examples
#' susor_exportfile(susor_qn_variable = "pupils_SLK"
#' susor_qn_version = 5)



susor_export_file = function(susor_qn_variable,
                          susor_qn_version,
                          susor_format = "STATA",
                          susor_interview_status = "All",
                          temporary_dir = tempdir(),
                          #dir_ss_downloads = tempdir(),
                          ...){

  #create directory to export data --------------------------------------------
  if (!dir.exists(susor_dir_downloads)) {

    dir.create(susor_dir_downloads)

  }


    # get questionnaire ID (susor_questionnaires is generated by susor_credentials)
    quid = susor_questionnaires %>% filter(Variable == susor_qn_variable & Version == susor_qn_version) %>% .$QuestionnaireIdentity


#generate file in the server ---------------------------------------------------
    post_export = susor_generate_file(
      susor_quid = quid,
      susor_format = susor_format
      )

    #get job ID from post to generate file
    JobID = post_export$jobID
    message(paste("JobID:",JobID))


#Function to get status of export in server (used so we can check until the file is completed)

    get_status = function(){

      #check export status
      Json_GET = tempfile(fileext = ".json")

      response_file_status =  GET(post_export$apiGenerate, #this query is generated by susor_generate_file()
                                  authenticate(susor_user, susor_password),
                                  encode = "json",
                                  write_disk(Json_GET, overwrite = T)
                                  )

      file_status_data = jsonlite::fromJSON(Json_GET)
      file_status = file_status_data[file_status_data$JobId == JobID,]$ExportStatus #status of file in server

      return(file_status)

    }

    #status of the file creation in the server
    file_status = get_status()

    #wait until the status is Completed so we can start exporting
    while (file_status != "Completed") {
      Sys.sleep(1)
      message(paste("Creating", susor_qn_variable, "version:", susor_qn_version, "in Server"))
      file_status = get_status()

    }

    message("File creation has been completed in the server! Starting download!")

#start exporting the file -------------------------------------------------
    #Define API to export
    apiExport = sprintf("%s/api/v2/export/%s/file", susor_server, JobID)

    #remove JobID so it can be redefined in future queries
    #rm(JobID)

    #export file
    response_export <- GET(apiExport, authenticate(susor_user, susor_password))

    #check response
    status = response_export$status_code
    check_response(status)



## Unzip and save in download directory (this directory must be defined in susor_credentials) ------------------------

    ## (this is the name of the file)
    unzip_name = paste0(susor_qn_variable,"_", susor_qn_version)
    zip_name = paste0(unzip_name,".zip")

    zipfile = file.path(temporary_dir,zip_name)

    ## directory where .zip is going to be extracted
    outputdir = file.path(susor_dir_downloads, unzip_name )

    if (!file.exists(outputdir)){

      dir.create(outputdir)

    }


    #open connection to write data in temporary directory
    filecon <- file(zipfile, "wb")
    #write data contents to download file!! change unzip folder to temporary file when in shiny
    writeBin(response_export$content, filecon)
    #close the connection
    close(filecon)


    ## unzip data into the export directory
    unzip(zipfile=zipfile, overwrite = TRUE,
          exdir = outputdir,
          unzip = "internal"
    )



    message(paste(susor_qn_variable, susor_qn_version, "has been exported to:", outputdir))



}
